export default {
  _views_diagnosis_alert_list: () => import('../../views/diagnosis/alert/list'),
  _views_diagnosis_dataDiagnosis_list: () => import('../../views/diagnosis/dataDiagnosis/list'),
  _views_diagnosis_dataDiagnosis_list_edit: () => import('../../views/diagnosis/dataDiagnosis/edit'),
  _views_diagnosis_dataDownload_list: () => import('../../views/diagnosis/dataDownload/list'),
  _views_diagnosis_dataFilling_list: () => import('../../views/diagnosis/dataFilling/list'),
  _views_diagnosis_dataFilling_dataFill: () => import('../../views/diagnosis/dataFilling/dataFill'),
  _views_diagnosis_indexMg_list: () => import('../../views/diagnosis/indexMg/list'),
  _views_diagnosis_indexMg_keyElements: () => import('../../views/diagnosis/indexMg/keyElements'),
  _views_diagnosis_questionnaire_list: () => import('../../views/diagnosis/questionnaire/list'),
  _views_diagnosis_questionnaire_template: () => import('../../views/diagnosis/questionnaire/template'),
  _views_diagnosis_reports_annualReportExport: () => import('../../views/diagnosis/reports/annualReportExport'),
  _views_diagnosis_reports_annualReportRelease: () => import('../../views/diagnosis/reports/annualReportRelease'),
  _views_diagnosis_reports_annualReportGeneration: () => import('../../views/diagnosis/reports/annualReportGeneration'),
  _views_diagnosis_reports_myReport: () => import('../../views/diagnosis/reports/myReport'),
  _views_diagnosis_reports_uploadAttachments: () => import('../../views/diagnosis/reports/uploadAttachments'),
  _views_diagnosis_valueSetting_list: () => import('../../views/diagnosis/valueSetting/list'),
  _views_diagnosis_valueSetting_edit: () => import('../../views/diagnosis/valueSetting/edit'),
}
